### ISSUE TITLE
Conflict between eslint rules "indent" and "react/jsx-indent-props"

### ISSUE THREAD

**Issue by lkazberova** [sayprimer/primer-client#2]
@juanplusjuan I suppose we have conflict between these rules. Please take a look at screenshots

We have first error from "react/jsx-indent-props" rule that should be 22 space
<img width="648" alt="screenshot 54" src="https://user-images.githubusercontent.com/13050551/51911262-d5ee6280-23ea-11e9-8348-6a73337830b4.png">
After applying this rule we have second error from "indent" rule that should be 24 space)
<img width="501" alt="screenshot 55" src="https://user-images.githubusercontent.com/13050551/51911182-9b84c580-23ea-11e9-9a38-d4745fa85444.png">

**Comment by juanplusjuan** [comment]
@lkazberova I believe this is fixed.  Here is the commit: https://github.com/sayprimer/primer-client/commit/052a3bf25d08e834ed5775984c7f154aabb42736

Let me know if it works!
