### ISSUE TITLE
User should be able to import a lead list to his Customer Dashboard

### ISSUE THREAD

**Issue by lkazberova** [sayprimer/primer-client#5]
@juanplusjuan please, can you provide example of imported file? Thank you!

**Comment by lkazberova** [comment]
Additional question regarding this task "User should be able to download lead list as CSV", can you provide desired format for it? Thank you!

**Comment by juanplusjuan** [comment]
@lkazberova Here are some examples.  Keith says we can ignore any field that isn't represented in the database.

https://www.dropbox.com/s/xvcrw2r8yhgx4jh/TOPFUNNEL%20FOR%20SCALE%20-%20no%20geo%20restrictions%20-%2010.16.18.csv?dl=0
https://www.dropbox.com/s/bc4824wspkpivlz/Amplitude%20leads%201.csv?dl=0
